const bookingState={selected:null,menu:null,baseFees:null};
function yen(n){return `${Number(n||0).toLocaleString("ja-JP")}円`}
function fallbackBaseFees(){return{items:[{id:"base",label:"基本運賃",price:2000,visible:true},{id:"dispatch",label:"予約配車料",price:500,visible:true},{id:"special",label:"特殊車両料",price:1000,visible:true}]}}
function fallbackMenu(){return{move_type:[{name:"車いす",price:0},{name:"ストレッチャー",price:4000},{name:"リクライニング車いす",price:2000}],assist:[{name:"乗降介助",price:1500},{name:"身体介助",price:3000},{name:"介助不要",price:0}],stairs:[{name:"階段介助なし",price:0},{name:"見守り介助",price:0},{name:"2階移動",price:3000},{name:"3階移動",price:5000}],equipment:[{name:"レンタルなし",price:0},{name:"車いすレンタル",price:500},{name:"ストレッチャー",price:4000}],round:[{name:"片道",price:0},{name:"往復",price:0},{name:"待機",price:1000},{name:"病院付き添い",price:1500}]}}
async function loadMenu(){try{const m=await apiGet(ENDPOINTS.getMenu);bookingState.menu={move_type:m.move_type||m.vehicle||[],assist:m.assist||[],stairs:m.stairs||[],equipment:m.equipment||[],round:m.round||[]}}catch{bookingState.menu=fallbackMenu()}try{const f=await apiGet(ENDPOINTS.baseFees);bookingState.baseFees=f.baseFees||fallbackBaseFees()}catch{bookingState.baseFees=fallbackBaseFees()}renderBaseFees();fillSelect("moveType",bookingState.menu.move_type,true);fillSelect("assistanceType",bookingState.menu.assist,false);fillSelect("stairAssistance",bookingState.menu.stairs,false);fillSelect("equipmentRental",bookingState.menu.equipment,false);fillSelect("roundTrip",bookingState.menu.round,false);updateWarnings();updateEstimate()}
function fillSelect(id,items,placeholder){const el=document.getElementById(id);el.innerHTML=(placeholder?`<option value="">選択してください</option>`:"")+(items||[]).map(x=>`<option value="${escapeHtml(x.name)}" data-price="${Number(x.price||0)}">${escapeHtml(x.name)}${Number(x.price||0)?`（+${Number(x.price||0).toLocaleString()}円）`:""}</option>`).join("")}
function renderBaseFees(){const items=(bookingState.baseFees?.items||[]).filter(x=>x.visible!==false);document.getElementById("baseFeeList").innerHTML=items.map(x=>`<p><strong>${escapeHtml(x.label)}</strong> ${yen(x.price)}</p>`).join("")}
function selectedPrice(id){const el=document.getElementById(id),op=el.options[el.selectedIndex];return Number(op?.dataset?.price||0)}
function updateEstimate(){const base=(bookingState.baseFees?.items||[]).filter(x=>x.visible!==false).reduce((s,x)=>s+Number(x.price||0),0);const total=base+selectedPrice("moveType")+selectedPrice("assistanceType")+selectedPrice("stairAssistance")+selectedPrice("equipmentRental")+selectedPrice("roundTrip");document.getElementById("estimateTotal").textContent=yen(total)}
function updateWarnings(){const stair=document.getElementById("stairAssistance").value;const move=document.getElementById("moveType").value;const equip=document.getElementById("equipmentRental").value;document.getElementById("stairWarning").classList.toggle("hidden",!(stair&&stair!=="階段介助なし"&&stair!=="見守り介助"));document.getElementById("wheelchairWarning").classList.toggle("hidden",!(move.includes("車いす")||equip.includes("車いす")));document.getElementById("stretcherWarning").classList.toggle("hidden",!(move.includes("ストレッチャー")||equip.includes("ストレッチャー")));updateEstimate()}
async function openBookingForm(date,time){bookingState.selected={date,time};document.getElementById("selectedSlot").textContent=`${date} ${time} から`;document.getElementById("bookingForm").classList.remove("hidden");document.getElementById("thanksView").classList.add("hidden");document.getElementById("bookingModal").classList.remove("hidden");await loadMenu()}
function closeModal(){document.getElementById("bookingModal").classList.add("hidden")}
function validTel(t){return /^0\d{9,10}$/.test(String(t||"").replace(/-/g,""))}
function validKana(v){return /^[ァ-ヶー\s　]+$/.test(String(v||"").trim())}
async function submitBooking(){const usageType=document.getElementById("usageType").value;const name=document.getElementById("customerKana").value.trim();const phone=document.getElementById("customerPhone").value.replace(/-/g,"").trim();const pickup=document.getElementById("pickupLocation").value.trim();const vehicle=document.getElementById("moveType").value;if(!document.getElementById("agree").checked)return toast("個人情報の同意が必要です");if(!usageType||!name||!phone||!pickup||!vehicle)return toast("必須項目を入力してください");if(!validKana(name))return toast("お名前はカタカナで入力してください");if(!validTel(phone))return toast("電話番号形式が正しくありません");const payload={usageType,name,kana:name,phone,date:bookingState.selected.date,time:bookingState.selected.time,pickup,destination:document.getElementById("destination").value.trim(),vehicle,assist:document.getElementById("assistanceType").value,stairs:document.getElementById("stairAssistance").value,equipment:document.getElementById("equipmentRental").value,roundTrip:document.getElementById("roundTrip").value,notes:document.getElementById("notes").value.trim(),estimate:document.getElementById("estimateTotal").textContent};try{document.getElementById("submitBooking").disabled=true;const res=await apiPost(ENDPOINTS.createReservation,payload);document.getElementById("thanksId").textContent=res.id||"";document.getElementById("bookingForm").classList.add("hidden");document.getElementById("thanksView").classList.remove("hidden");await loadCalendarData()}catch(e){toast(e.message)}finally{document.getElementById("submitBooking").disabled=false}}
document.addEventListener("DOMContentLoaded",()=>{["moveType","assistanceType","stairAssistance","equipmentRental","roundTrip"].forEach(id=>document.getElementById(id).addEventListener("change",updateWarnings));document.getElementById("closeModal").addEventListener("click",closeModal);document.getElementById("closeThanks").addEventListener("click",closeModal);document.getElementById("submitBooking").addEventListener("click",submitBooking)})
