const bookingState={selected:null,menu:null,baseFees:null};
function yen(n){return`${Number(n||0).toLocaleString("ja-JP")}円`}
function fallbackBaseFees(){return{items:[{id:"base",label:"基本運賃",price:2000,visible:true},{id:"dispatch",label:"予約配車料",price:500,visible:true},{id:"special",label:"特殊車両料",price:1000,visible:true}],note:"走行距離・待機時間・追加介助により最終金額は変動する場合があります。"}}
function fallbackMenu(){return{move_type:[{name:"車いす",price:0},{name:"ストレッチャー",price:4000},{name:"リクライニング車いす",price:2000}],assist:[{name:"乗降介助",price:1500},{name:"身体介助",price:3000},{name:"介助不要",price:0}],stairs:[{name:"階段介助なし",price:0},{name:"見守り介助",price:0},{name:"2階移動",price:3000},{name:"3階移動",price:5000}],equipment:[{name:"レンタルなし",price:0},{name:"車いすレンタル",price:500},{name:"ストレッチャー",price:4000}],round:[{name:"片道",price:0},{name:"往復",price:0},{name:"待機",price:1000},{name:"病院付き添い",price:1500}]}}
async function loadMenuForBooking(){try{const m=await apiGet(ENDPOINTS.getMenu);bookingState.menu={move_type:m.move_type||m.vehicle||[],assist:m.assist||[],stairs:m.stairs||[],equipment:m.equipment||[],round:m.round||[]}}catch{bookingState.menu=fallbackMenu()}try{const fees=await apiGet(ENDPOINTS.baseFees);bookingState.baseFees=fees.baseFees||fallbackBaseFees()}catch{bookingState.baseFees=fallbackBaseFees()}renderBaseFees();fillSelect("moveType",bookingState.menu.move_type||[],true);fillSelect("assistanceType",bookingState.menu.assist||[],false);fillSelect("stairAssistance",bookingState.menu.stairs||[],false);fillSelect("equipmentRental",bookingState.menu.equipment||[],false);fillSelect("roundTrip",bookingState.menu.round||[],false);applyAutoWarnings();updateEstimate()}
function renderBaseFees(){const fees=bookingState.baseFees||fallbackBaseFees();document.getElementById("baseFeeList").innerHTML=(fees.items||[]).filter(x=>x.visible!==false).map(item=>`<p><strong>${escapeHtml(item.label)}</strong><span>${yen(item.price)}</span></p>`).join("")}
function fillSelect(id,items,placeholder){const el=document.getElementById(id);el.innerHTML=(placeholder?`<option value="">選択してください</option>`:"")+(items||[]).map(item=>`<option value="${escapeHtml(item.name)}" data-price="${Number(item.price||0)}">${escapeHtml(item.name)}${Number(item.price||0)?`（+${Number(item.price||0).toLocaleString()}円）`:""}</option>`).join("")}
function selectedPrice(id){const el=document.getElementById(id),opt=el?.options?.[el.selectedIndex];return Number(opt?.dataset?.price||0)}
function updateEstimate(){const fees=bookingState.baseFees||fallbackBaseFees();const base=(fees.items||[]).filter(x=>x.visible!==false).reduce((s,x)=>s+Number(x.price||0),0);const menu=selectedPrice("moveType")+selectedPrice("assistanceType")+selectedPrice("stairAssistance")+selectedPrice("equipmentRental")+selectedPrice("roundTrip");document.getElementById("estimateTotal").textContent=yen(base+menu)}
function applyAutoWarnings(){const stair=document.getElementById("stairAssistance").value;const equip=document.getElementById("equipmentRental").value;const move=document.getElementById("moveType").value;document.getElementById("stairWarning").classList.toggle("hidden",!(stair&&stair!=="階段介助なし"&&stair!=="見守り介助"));document.getElementById("wheelchairWarning").classList.toggle("hidden",!(move.includes("車いす")||equip.includes("車いす")));document.getElementById("stretcherWarning").classList.toggle("hidden",!(move.includes("ストレッチャー")||equip.includes("ストレッチャー")));if((stair&&stair!=="階段介助なし"&&stair!=="見守り介助")||(move.includes("ストレッチャー")||equip.includes("ストレッチャー"))){const assist=document.getElementById("assistanceType");Array.from(assist.options).forEach(o=>{if(o.value==="身体介助")assist.value=o.value})}updateEstimate()}
async function openBookingForm(date,time){bookingState.selected={date,time};document.getElementById("selectedSlotInfo").textContent=`${date} ${time} から`;document.getElementById("bookingFormView").classList.remove("hidden");document.getElementById("bookingThanksView").classList.add("hidden");document.getElementById("bookingModal").classList.remove("hidden");await loadMenuForBooking()}
function closeBookingForm(){document.getElementById("bookingModal").classList.add("hidden")}function validTel(tel){return/^0\d{9,10}$/.test(String(tel||"").replace(/-/g,""))}function validKana(v){return /^[ァ-ヶー\s　]+$/.test(String(v||"").trim())}
async function submitBooking(){if(!bookingState.selected)return toast("日時を選択してください");const usageType=document.getElementById("usageType").value,kana=document.getElementById("customerKana").value.trim(),phone=document.getElementById("customerPhone").value.replace(/-/g,"").trim(),pickup=document.getElementById("pickupLocation").value.trim(),destination=document.getElementById("destination").value.trim(),moveType=document.getElementById("moveType").value;if(!document.getElementById("agree").checked)return toast("個人情報の同意が必要です");if(!usageType||!kana||!phone||!pickup||!moveType)return toast("必須項目を入力してください");if(!validKana(kana))return toast("お名前はカタカナで入力してください");if(!validTel(phone))return toast("電話番号形式が正しくありません");const payload={usageType,name:kana,kana,phone,date:bookingState.selected.date,time:bookingState.selected.time,pickup,destination,vehicle:moveType,assist:document.getElementById("assistanceType").value,stairs:document.getElementById("stairAssistance").value,equipment:document.getElementById("equipmentRental").value,roundTrip:document.getElementById("roundTrip").value,notes:document.getElementById("notes").value.trim(),estimate:document.getElementById("estimateTotal").textContent};try{document.getElementById("submitBookingBtn").disabled=true;const res=await apiPost(ENDPOINTS.createReservation,payload);if(!res.success)throw new Error(res.message||"予約に失敗しました");document.getElementById("thanksReservationId").textContent=res.id||"";document.getElementById("bookingFormView").classList.add("hidden");document.getElementById("bookingThanksView").classList.remove("hidden");await loadCalendarData()}catch(e){toast(e.message||"通信エラー")}finally{document.getElementById("submitBookingBtn").disabled=false}}
document.addEventListener("DOMContentLoaded",()=>{["moveType","assistanceType","stairAssistance","equipmentRental","roundTrip"].forEach(id=>document.getElementById(id)?.addEventListener("change",()=>{applyAutoWarnings();updateEstimate()}));document.getElementById("closeBookingBtn")?.addEventListener("click",closeBookingForm);document.getElementById("closeThanksBtn")?.addEventListener("click",closeBookingForm);document.getElementById("submitBookingBtn")?.addEventListener("click",submitBooking)});
