export default {
  async fetch(request, env) {
    const headers={"Content-Type":"application/json; charset=UTF-8","Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"};
    if(request.method==="OPTIONS")return new Response(null,{headers});
    try{
      if(!env.DB)return json({success:false,message:"DB_BINDING_MISSING"},500,headers);
      await ensureSchema(env.DB);
      await cleanupStaleAutoBlocks(env.DB);
      const url=new URL(request.url),path=url.pathname;
      if(path==="/")return new Response("OK");
      if(path==="/api/bootstrap"){return json({success:true,settings:await getSettingsObject(env.DB),uiTexts:await getUiTexts(env.DB),menu:await getMenu(env.DB),baseFees:await getBaseFees(env.DB)},200,headers)}
      if(path==="/api/rangeData"){const start=url.searchParams.get("start")||"",end=url.searchParams.get("end")||"";const blocks=await env.DB.prepare(`SELECT id,date,time,type,reservation_id FROM blocks WHERE date>=? AND date<=? ORDER BY date,time`).bind(start,end).all();return json({success:true,blocks:blocks.results||[],settings:await getSameDaySettings(env.DB)},200,headers)}
      if(path==="/api/getBlocks"){const blocks=await env.DB.prepare(`SELECT id,date,time,type,reservation_id FROM blocks ORDER BY date,time`).all();return json({success:true,blocks:blocks.results||[]},200,headers)}
      if(path==="/api/getReservations"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);const rows=await env.DB.prepare(`SELECT * FROM reservations WHERE is_visible != 0 ORDER BY created_at DESC,id DESC`).all();return json(rows.results||[],200,headers)}
      if(path==="/api/menu")return json(await getMenu(env.DB),200,headers);
      if(path==="/api/baseFees")return json({baseFees:await getBaseFees(env.DB)},200,headers);
      if(path==="/api/uiTexts")return json({success:true,uiTexts:await getUiTexts(env.DB)},200,headers);
      if(path==="/api/admin/login"&&request.method==="POST"){const body=await safeJson(request);const saved=await getSetting(env.DB,"admin_password","1234");if(String(body.password||"")!==String(saved))return json({success:false,message:"認証に失敗しました"},200,headers);const token=(crypto.randomUUID?crypto.randomUUID():`${Date.now()}_${Math.random()}`);const expiresAt=Date.now()+12*60*60*1000;await setSetting(env.DB,"admin_session_token",token);await setSetting(env.DB,"admin_session_expires_at",String(expiresAt));return json({success:true,token,expiresAt},200,headers)}
      if(path==="/api/admin/logout"&&request.method==="POST"){if(await isAdminAuthorized(request,env.DB)){await setSetting(env.DB,"admin_session_token","");await setSetting(env.DB,"admin_session_expires_at","0")}return json({success:true},200,headers)}
      if(path==="/api/createReservation"&&request.method==="POST"){const body=await safeJson(request);for(const key of["usageType","name","phone","date","time","pickup","vehicle"]){if(!String(body[key]||"").trim())return json({success:false,message:"必須項目が未入力です"},400,headers)}const date=normalizeDate(body.date),time=normalizeTime(body.time);if(!date||!time)return json({success:false,message:"日時が不正です"},400,headers);const blockCount=getBlockCount(body.roundTrip);const slots=makeSlots(date,time,blockCount);for(const slot of slots){const exists=await env.DB.prepare(`SELECT id FROM blocks WHERE date=? AND time=? LIMIT 1`).bind(slot.date,slot.time).first();if(exists)return json({success:false,message:"この枠は予約できません"},409,headers)}const id=await nextReservationId(env.DB,date,time);await env.DB.prepare(`INSERT INTO reservations (id,usageType,name,kana,phone,date,time,pickup,destination,vehicle,transfer,assist,stairs,equipment,roundTrip,notes,estimate,baseFeeTotal,serviceFeeTotal,block_count,status,is_visible,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,String(body.usageType||""),String(body.name||""),String(body.kana||body.name||""),String(body.phone||""),date,time,String(body.pickup||""),String(body.destination||""),String(body.vehicle||""),String(body.transfer||""),String(body.assist||""),String(body.stairs||""),String(body.equipment||""),String(body.roundTrip||""),String(body.notes||""),String(body.estimate||""),Number(body.baseFeeTotal||0),Number(body.serviceFeeTotal||0),blockCount,"active",1,new Date().toISOString()).run();for(const slot of slots){await env.DB.prepare(`INSERT OR IGNORE INTO blocks (date,time,type,reservation_id,created_at) VALUES (?,?,?,?,?)`).bind(slot.date,slot.time,"auto",id,new Date().toISOString()).run()}await notify(env.DB,body,id);return json({success:true,id},200,headers)}
      if(path==="/api/cancelReservation"&&request.method==="POST"){const body=await safeJson(request);const id=String(body.id||"");if(!id)return json({success:false,message:"id required"},400,headers);await env.DB.prepare(`DELETE FROM blocks WHERE reservation_id=? AND type='auto'`).bind(id).run();await env.DB.prepare(`UPDATE reservations SET status='cancel' WHERE id=?`).bind(id).run();return json({success:true},200,headers)}
      if(path==="/api/admin/reservations/update"&&request.method==="POST"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);const body=await safeJson(request);await env.DB.prepare(`UPDATE reservations SET status=? WHERE id=?`).bind(String(body.status||"active"),String(body.id||"")).run();if(String(body.status)==="cancel")await env.DB.prepare(`DELETE FROM blocks WHERE reservation_id=? AND type='auto'`).bind(String(body.id||"")).run();return json({success:true},200,headers)}
      if(path==="/api/admin/reservations/hide"&&request.method==="POST"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);const body=await safeJson(request);await env.DB.prepare(`UPDATE reservations SET is_visible=0 WHERE id=?`).bind(String(body.id||"")).run();return json({success:true},200,headers)}
      if(path==="/api/admin/reservations/csv"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);const rows=await env.DB.prepare(`SELECT * FROM reservations ORDER BY created_at DESC`).all();return new Response(toCsv(rows.results||[]),{headers:{"Content-Type":"text/csv; charset=UTF-8","Content-Disposition":"attachment; filename=reservations.csv","Access-Control-Allow-Origin":"*"}})}
      if(path==="/api/admin/settings"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);return json({success:true,settings:await getSettingsObject(env.DB)},200,headers)}
      if(path==="/api/admin/settings/save"&&request.method==="POST"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);const body=await safeJson(request);for(const [k,v] of Object.entries(body)){if(k!=="new_password")await setSetting(env.DB,k,String(v??""))}return json({success:true},200,headers)}
      if(path==="/api/admin/password/change"&&request.method==="POST"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);const body=await safeJson(request);const saved=await getSetting(env.DB,"admin_password","1234");if(String(body.current||"")!==String(saved))return json({success:false,message:"現在PWが違います"},403,headers);if(!String(body.next||"").trim())return json({success:false,message:"新PWが空です"},400,headers);await setSetting(env.DB,"admin_password",String(body.next));return json({success:true},200,headers)}
      if(path==="/api/admin/menu/save"&&request.method==="POST"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);const body=await safeJson(request);await setSetting(env.DB,"menu_items",JSON.stringify(body.items||[]));await setSetting(env.DB,"menu_groups",JSON.stringify(body.groups||[]));return json({success:true},200,headers)}
      if(path==="/api/admin/baseFees/save"&&request.method==="POST"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);const body=await safeJson(request);await setSetting(env.DB,"base_fees",JSON.stringify(body.items||defaultBaseFees().items));return json({success:true},200,headers)}
      if(path==="/api/admin/uiTexts/save"&&request.method==="POST"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);const body=await safeJson(request);await setSetting(env.DB,"ui_texts",JSON.stringify(body.uiTexts||{}));return json({success:true},200,headers)}
      if(path==="/api/admin/logo/upload"&&request.method==="POST"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);const body=await safeJson(request);await setSetting(env.DB,"logo_url",String(body.dataUrl||""));return json({success:true,url:String(body.dataUrl||"")},200,headers)}
      if(path==="/api/admin/blocks/slot"&&request.method==="POST"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);const body=await safeJson(request);const date=normalizeDate(body.date),time=normalizeTime(body.time),mode=String(body.mode||"block");if(!date||!time)return json({success:false,message:"日時が不正です"},400,headers);if(mode==="unblock")await env.DB.prepare(`DELETE FROM blocks WHERE date=? AND time=? AND type='manual'`).bind(date,time).run();else await env.DB.prepare(`INSERT OR IGNORE INTO blocks (date,time,type,reservation_id,created_at) VALUES (?,?,'manual','',?)`).bind(date,time,new Date().toISOString()).run();return json({success:true},200,headers)}
      if(path==="/api/admin/blocks/day"&&request.method==="POST"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);const body=await safeJson(request);const date=normalizeDate(body.date),scope=String(body.scope||"day");if(!date)return json({success:false,message:"日付が不正です"},400,headers);const times=scopeTimes(scope);if(!times.length)return json({success:false,message:"範囲が不正です"},400,headers);const placeholders=times.map(()=>"?").join(",");const manual=await env.DB.prepare(`SELECT COUNT(*) AS c FROM blocks WHERE date=? AND type='manual' AND time IN (${placeholders})`).bind(date,...times).first();const shouldUnblock=String(body.mode||"")==="unblock"||(String(body.mode||"")==="toggle"&&Number(manual?.c||0)>0);if(shouldUnblock){await env.DB.prepare(`DELETE FROM blocks WHERE date=? AND type='manual' AND time IN (${placeholders})`).bind(date,...times).run()}else{for(const time of times)await env.DB.prepare(`INSERT OR IGNORE INTO blocks (date,time,type,reservation_id,created_at) VALUES (?,?,'manual','',?)`).bind(date,time,new Date().toISOString()).run()}return json({success:true},200,headers)}
      if(path==="/api/admin/blocks/timeRange"&&request.method==="POST"){if(!(await isAdminAuthorized(request,env.DB)))return json({success:false,message:"Unauthorized"},401,headers);const body=await safeJson(request);const date=normalizeDate(body.date),start=normalizeTime(body.start),end=normalizeTime(body.end),mode=String(body.mode||"block");if(!date||!start||!end)return json({success:false,message:"指定が不正です"},400,headers);for(const time of buildRangeTimes(start,end)){if(mode==="unblock")await env.DB.prepare(`DELETE FROM blocks WHERE date=? AND time=? AND type='manual'`).bind(date,time).run();else await env.DB.prepare(`INSERT OR IGNORE INTO blocks (date,time,type,reservation_id,created_at) VALUES (?,?,'manual','',?)`).bind(date,time,new Date().toISOString()).run()}return json({success:true},200,headers)}
      return json({success:false,message:"Not Found"},404,headers)
    }catch(e){return json({success:false,message:`ERROR: ${e.message}`},500,headers)}
  }
};
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers})}async function safeJson(request){try{return await request.json()}catch{return{}}}
function bearerToken(request){const h=request.headers.get("Authorization")||"";const m=h.match(/^Bearer\s+(.+)$/i);return m?m[1].trim():""}
async function isAdminAuthorized(request,db){const token=bearerToken(request);if(!token)return false;const saved=await getSetting(db,"admin_session_token",""),exp=Number(await getSetting(db,"admin_session_expires_at","0")||0);if(!saved||token!==saved)return false;if(exp<=Date.now())return false;return true}
async function ensureSchema(db){await db.prepare(`CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY,value TEXT)`).run();await db.prepare(`INSERT OR IGNORE INTO settings (key,value) VALUES ('admin_password','1234')`).run();await db.prepare(`CREATE TABLE IF NOT EXISTS reservations (id TEXT PRIMARY KEY)`).run();for(const [c,t] of Object.entries({usageType:"TEXT",name:"TEXT",kana:"TEXT",phone:"TEXT",date:"TEXT",time:"TEXT",pickup:"TEXT",destination:"TEXT",vehicle:"TEXT",transfer:"TEXT",assist:"TEXT",stairs:"TEXT",equipment:"TEXT",roundTrip:"TEXT",notes:"TEXT",estimate:"TEXT",baseFeeTotal:"INTEGER DEFAULT 0",serviceFeeTotal:"INTEGER DEFAULT 0",block_count:"INTEGER DEFAULT 2",status:"TEXT DEFAULT 'active'",is_visible:"INTEGER DEFAULT 1",created_at:"TEXT"}))await addColumnIfMissing(db,"reservations",c,t);await db.prepare(`CREATE TABLE IF NOT EXISTS blocks (id INTEGER PRIMARY KEY AUTOINCREMENT,date TEXT,time TEXT,type TEXT,reservation_id TEXT,created_at TEXT)`).run();await db.prepare(`CREATE UNIQUE INDEX IF NOT EXISTS idx_blocks_unique ON blocks(date,time)`).run()}
async function cleanupStaleAutoBlocks(db){await db.prepare(`DELETE FROM blocks WHERE type='auto' AND (reservation_id IS NULL OR reservation_id='' OR NOT EXISTS (SELECT 1 FROM reservations r WHERE r.id=blocks.reservation_id AND COALESCE(r.status,'active')!='cancel' AND COALESCE(r.is_visible,1)!=0))`).run()}
async function addColumnIfMissing(db,table,column,type){const info=await db.prepare(`PRAGMA table_info(${table})`).all();if(!(info.results||[]).some(r=>r.name===column))await db.prepare(`ALTER TABLE ${table} ADD COLUMN ${column} ${type}`).run()}
async function getSetting(db,key,fallback){const row=await db.prepare(`SELECT value FROM settings WHERE key=? LIMIT 1`).bind(key).first();return row?row.value:fallback}async function setSetting(db,key,value){await db.prepare(`INSERT INTO settings (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value`).bind(key,value).run()}
async function getSettingsObject(db){const keys=["notify_webhook_url","logo_text","logo_subtext","logo_url","github_user","github_repo","github_branch","github_path","github_pat","same_day_enabled","min_hours"];const obj={};for(const k of keys)obj[k]=await getSetting(db,k,k==="same_day_enabled"?"true":k==="min_hours"?"3":"");return obj}async function getSameDaySettings(db){return{same_day_enabled:await getSetting(db,"same_day_enabled","true"),min_hours:await getSetting(db,"min_hours","3")}}
function defaultBaseFees(){return{items:[{id:"base",label:"基本運賃",price:2000,visible:true},{id:"dispatch",label:"予約配車料",price:500,visible:true},{id:"special",label:"特殊車両料",price:1000,visible:true}]}}async function getBaseFees(db){const saved=await getSetting(db,"base_fees","");if(saved){try{return{items:JSON.parse(saved)}}catch{}}return defaultBaseFees()}
async function getUiTexts(db){const saved=await getSetting(db,"ui_texts","");if(saved){try{return JSON.parse(saved)}catch{}}return{}}
function normalizeDate(v){const s=String(v||"").trim();return/^\d{4}-\d{2}-\d{2}$/.test(s)?s:""}function normalizeTime(v){const s=String(v||"").trim();if(/^\d{2}:\d{2}$/.test(s))return s;if(/^\d{1,2}:\d{2}$/.test(s)){const[h,m]=s.split(":");return`${String(h).padStart(2,"0")}:${m}`}return""}
async function nextReservationId(db,date,time){const base=`${String(date).replace(/-/g,"")}${String(time).replace(/:/g,"")}`;let id=base,seq=1;while(await db.prepare(`SELECT id FROM reservations WHERE id=? LIMIT 1`).bind(id).first()){seq+=1;id=`${base}-${String(seq).padStart(2,"0")}`}return id}
function getBlockCount(roundTrip){const v=String(roundTrip||"");if(["往復","待機","付き添い","病院付き添い"].some(x=>v.includes(x)))return 4;return 2}
function makeSlots(date,time,count){
  const [y,m,d]=String(date).split("-").map(Number),[h,min]=String(time).split(":").map(Number);
  if(!y||!m||!d||Number.isNaN(h)||Number.isNaN(min))return[];
  const start=h*60+min,slots=[];
  for(let i=0;i<count;i++){
    const total=start+i*30,dayOffset=Math.floor(total/1440),minuteOfDay=((total%1440)+1440)%1440;
    const slotDate=new Date(y,m-1,d);slotDate.setDate(slotDate.getDate()+dayOffset);
    slots.push({
      date:`${slotDate.getFullYear()}-${String(slotDate.getMonth()+1).padStart(2,"0")}-${String(slotDate.getDate()).padStart(2,"0")}`,
      time:`${String(Math.floor(minuteOfDay/60)).padStart(2,"0")}:${String(minuteOfDay%60).padStart(2,"0")}`
    });
  }
  return slots;
}
function buildAllTimes(){const out=[];for(let h=0;h<=23;h++)for(let m=0;m<60;m+=30)out.push(`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`);return out}
function buildNormalTimes(){const out=[];for(let h=6;h<=21;h++){for(let m=0;m<60;m+=30){if(h===21&&m>0)continue;out.push(`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`)}}return out}function buildRangeTimes(start,end){const out=[];let [sh,sm]=start.split(":").map(Number),[eh,em]=end.split(":").map(Number);let s=sh*60+sm,e=eh*60+em;for(let t=s;t<e;t+=30)out.push(`${String(Math.floor(t/60)).padStart(2,"0")}:${String(t%60).padStart(2,"0")}`);return out}
function buildNightTimes(){return [...buildRangeTimes("00:00","06:00"),...buildRangeTimes("21:30","24:00")]}
function scopeTimes(scope){if(scope==="all")return buildAllTimes();if(scope==="night")return buildNightTimes();return buildNormalTimes()}
function inferLegacyGroup(name){const n=String(name||"");if(["車いす","ストレッチャー","リクライニング車いす"].includes(n))return"move_type";if(["乗降介助","身体介助","介助不要"].includes(n))return"assist";if(["階段介助なし","見守り介助","2階移動","3階移動"].includes(n))return"stairs";if(["レンタルなし","車いすレンタル"].includes(n))return"equipment";if(["片道","往復","待機","病院付き添い"].includes(n))return"round";return"custom"}
async function getMenu(db){const saved=await getSetting(db,"menu_items","");const groupSaved=await getSetting(db,"menu_groups","");let groups=[];try{groups=groupSaved?JSON.parse(groupSaved):[]}catch{}if(saved){try{const items=JSON.parse(saved),grouped={move_type:[],assist:[],stairs:[],equipment:[],round:[],custom:[],groups};items.forEach(i=>{const raw=i.group||"custom";const g=(raw==="custom"||!raw)?inferLegacyGroup(i.name):raw;if(grouped[g])grouped[g].push({...i,group:g});else grouped.custom.push({...i,group:g})});return grouped}catch{}}return{groups,move_type:[{name:"車いす",price:0,visible:true},{name:"ストレッチャー",price:4000,visible:true},{name:"リクライニング車いす",price:2000,visible:true}],assist:[{name:"乗降介助",price:1500,visible:true},{name:"身体介助",price:3000,visible:true},{name:"介助不要",price:0,visible:true}],stairs:[{name:"階段介助なし",price:0,visible:true},{name:"見守り介助",price:0,visible:true},{name:"2階移動",price:3000,visible:true},{name:"3階移動",price:5000,visible:true}],equipment:[{name:"レンタルなし",price:0,visible:true},{name:"車いすレンタル",price:500,visible:true},{name:"ストレッチャー",price:4000,visible:true}],round:[{name:"片道",price:0,multiplier:1,visible:true},{name:"往復",price:0,multiplier:2,visible:true},{name:"待機",price:1000,multiplier:1,visible:true},{name:"病院付き添い",price:1500,multiplier:1,visible:true}]}}
function toCsv(rows){const cols=["id","usageType","name","kana","phone","date","time","pickup","destination","vehicle","transfer","assist","stairs","equipment","roundTrip","estimate","baseFeeTotal","serviceFeeTotal","status","is_visible","created_at"];const esc=v=>`"${String(v??"").replace(/"/g,'""')}"`;return"\ufeff"+[cols.join(","),...rows.map(r=>cols.map(c=>esc(r[c])).join(","))].join("\n")}
async function notify(db,body,id){const url=await getSetting(db,"notify_webhook_url","");if(!url)return;try{await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"reservation_created",id,body})})}catch{}}
